PROJECT_NAME: "rlffr"

MODEL_NAME: "Qwen/Qwen3-8B"
QUESTION_SRC: "obalcells/longfact-augmented-prompts"

MODEL_CHECKPOINTS: "outputs/checkpoints"
DB_PATH: "outputs/compilation.db"

DATASET_LEN: 20000
